### ISSUE TITLE
Getting an account

### ISSUE THREAD

**Issue by marcosscriven** [mondough/docs#44]
I've signed up for one of your accounts to try this, but it says I'm 70,000 or so behind.
Is there a way to get a test account while I wait please?

**Comment by obeattie** [comment]
You can get bumped up by using the share links in the app, and encouraging friends to sign up 😉

**Comment by marcosscriven** [comment]
Ah ok - I was hoping a technical interest might be sufficient. I'm not really looking to be a marketing machine!
